table fact_vencimentos
	lineageTag: d5136436-11c5-4ebd-97fe-346275a9451a

	measure 'Vencimentos na data' = SUM('fact_vencimentos'[Valor])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: c8a14f6b-29ba-45c4-83d7-3a5b0c9ff5d7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Vencimentos na data útil' = ```
					CALCULATE(
						SUM('fact_vencimentos'[Valor]),
						USERELATIONSHIP('ponte_dias_uteis'[Data], 'fact_vencimentos'[DataVencimento])
					)
				
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: e9702ca0-00fc-4e47-ba19-298a9cf88595

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DataVencimento
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2f366497-444e-410f-8846-d3ded35d1b0d
		summarizeBy: none
		sourceColumn: DataVencimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valor
		dataType: decimal
		isHidden
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 2fdff58c-81ed-43bd-a2e2-fc8d01c02ddb
		summarizeBy: sum
		sourceColumn: Valor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition fact_vencimentos = m
		mode: import
		source = ```
				let
				    Fonte = 
				    "DataVencimento;Valor
				2025-01-01;1303,45
				2025-01-01;1827,64
				2025-01-01;1436,72
				2025-01-02;1629,26
				2025-01-02;1204,15
				2025-01-03;1572,09
				2025-01-04;325,44
				2025-01-04;1690,56
				2025-01-04;383,13
				2025-01-05;1399,68
				2025-01-05;1190,41
				2025-01-05;758,96
				2025-01-05;1419,07
				2025-01-06;765,6
				2025-01-06;1347,86
				2025-01-07;604,69
				2025-01-08;1751,42
				2025-01-08;637,01
				2025-01-09;572,92
				2025-01-09;1813,38
				2025-01-10;1872,9
				2025-01-11;1745,37
				2025-01-11;931,98
				2025-01-11;954,53
				2025-01-11;1488,01
				2025-01-12;457,18
				2025-01-12;1525,38
				2025-01-12;1256,91
				2025-01-13;230,69
				2025-01-13;541,18
				2025-01-13;1266,48
				2025-01-15;1706,67
				2025-01-15;1381,53
				2025-01-15;712,36
				2025-01-15;1087,49
				2025-01-16;229,63
				2025-01-16;260,04
				2025-01-16;1873,47
				2025-01-16;328
				2025-01-16;1798,97
				2025-01-17;272,49
				2025-01-18;1836,74
				2025-01-18;1519,06
				2025-01-19;1997,01
				2025-01-19;1375,54
				2025-01-19;1206,46
				2025-01-20;972,72
				2025-01-20;1331,25
				2025-01-20;1137,69
				2025-01-21;1750,43
				2025-01-21;1755,48
				2025-01-22;847,71
				2025-01-22;1668,49
				2025-01-22;1338,67
				2025-01-22;256,38
				2025-01-22;562,96
				2025-01-22;1534,48
				2025-01-23;466,72
				2025-01-23;878,08
				2025-01-23;507,9
				2025-01-23;1123,61
				2025-01-23;1845,2
				2025-01-23;1780,39
				2025-01-24;629,91
				2025-01-24;1164,77
				2025-01-24;705,92
				2025-01-24;684,03
				2025-01-25;1970,81
				2025-01-25;849,99
				2025-01-25;313,22
				2025-01-26;950,13
				2025-01-26;275,75
				2025-01-26;1338,58
				2025-01-26;258,88
				2025-01-26;1871,19
				2025-01-27;1693,13
				2025-01-27;1140,96
				2025-01-28;1751,71
				2025-01-28;200,66
				2025-01-28;901,29
				2025-01-28;1050,94
				2025-01-29;1534,03
				2025-01-30;1456,58
				2025-01-30;1111,06
				2025-01-30;959,1
				2025-01-30;1134,07
				2025-01-30;1367,67
				2025-01-31;697,79
				2025-01-31;471,48
				2025-01-31;1215,91
				2025-02-01;1374,11
				2025-02-01;1794,54
				2025-02-01;547,4
				2025-02-02;1954,77
				2025-02-02;566
				2025-02-03;1662
				2025-02-03;1450,05
				2025-02-03;1652,72
				2025-02-03;1539,33
				2025-02-04;1544,73
				2025-02-05;1778,34
				2025-02-06;414,21
				2025-02-06;322,62
				2025-02-06;1158,95
				2025-02-06;300,48
				2025-02-06;342,11
				2025-02-07;501,15
				2025-02-07;534,79
				2025-02-07;1043,99
				2025-02-08;415,66
				2025-02-08;1043,82
				2025-02-08;394,84
				2025-02-08;296,92
				2025-02-09;1185,46
				2025-02-10;551,44
				2025-02-10;1989,11
				2025-02-10;1025,49
				2025-02-11;1162,37
				2025-02-11;1453,65
				2025-02-11;1577,25
				2025-02-12;669,84
				2025-02-12;1878,3
				2025-02-12;248,58
				2025-02-12;1266,86
				2025-02-13;786,1
				2025-02-14;1872,01
				2025-02-14;1451,2
				2025-02-14;1957,82
				2025-02-15;1420,4
				2025-02-15;803,8
				2025-02-15;316,62
				2025-02-15;592,25
				2025-02-15;812,57
				2025-02-16;231,68
				2025-02-17;386,45
				2025-02-17;1673,99
				2025-02-17;1234,04
				2025-02-18;1892,07
				2025-02-18;1510,07
				2025-02-19;1797,51
				2025-02-20;924,52
				2025-02-20;1518,35
				2025-02-20;1980,83
				2025-02-20;1812,78
				2025-02-21;787,13
				2025-02-21;1175,25
				2025-02-21;926,26
				2025-02-21;465,55
				2025-02-21;1028,32
				2025-02-22;932,88
				2025-02-22;1766,29
				2025-02-23;1318,45
				2025-02-23;743,57
				2025-02-24;936,24
				2025-02-24;427,29
				2025-02-24;220,38
				2025-02-24;225,31
				2025-02-25;1168,78
				2025-02-25;1460,55
				2025-02-25;1102,38
				2025-02-25;1308,93
				2025-02-26;912,25
				2025-02-26;1582,46
				2025-02-27;1783,3
				2025-02-27;1117,96
				2025-02-28;1871,28
				2025-02-28;1807,82
				2025-02-28;1734,37
				2025-03-01;1238,27
				2025-03-02;1916,37
				2025-03-02;553,49
				2025-03-03;1767,98
				2025-03-03;296,67
				2025-03-03;965,52
				2025-03-03;1464,3
				2025-03-04;1169,92
				2025-03-04;1936,19
				2025-03-04;1710,34
				2025-03-04;887,87
				2025-03-04;1583,83
				2025-03-05;1820,35
				2025-03-05;553,95
				2025-03-05;1967,8
				2025-03-05;996,45
				2025-03-05;1955,78
				2025-03-05;217,28
				2025-03-05;1284,81
				2025-03-05;1565,61
				2025-03-05;1574,57
				2025-03-06;268,45
				2025-03-06;1115,41
				2025-03-06;246,76
				2025-03-06;609,83
				2025-03-06;1158,85
				2025-03-07;1984,94
				2025-03-07;1512,17
				2025-03-08;290,21
				2025-03-08;1974,33
				2025-03-08;1393,93
				2025-03-09;863,88
				2025-03-09;1197,04
				2025-03-09;665,76
				2025-03-10;582,79
				2025-03-10;1491,51
				2025-03-10;470,18
				2025-03-12;248,19
				2025-03-12;938
				2025-03-13;716,23
				2025-03-13;236,78
				2025-03-14;1631,07
				2025-03-14;350,83
				2025-03-15;1337,24
				2025-03-15;1515,71
				2025-03-16;1351,66
				2025-03-16;1885,85
				2025-03-17;1865,63
				2025-03-17;1814,19
				2025-03-17;412,26
				2025-03-17;917,38
				2025-03-17;1018,18
				2025-03-18;1244,26
				2025-03-18;1255,4
				2025-03-18;817,62
				2025-03-19;874,25
				2025-03-19;859,86
				2025-03-19;1283,45
				2025-03-19;967,09
				2025-03-20;1107,68
				2025-03-21;588,71
				2025-03-21;1309,93
				2025-03-22;1087,58
				2025-03-22;562,73
				2025-03-22;384,95
				2025-03-23;729,63
				2025-03-23;598,48
				2025-03-24;1513,2
				2025-03-24;716,1
				2025-03-25;1376,87
				2025-03-26;458,3
				2025-03-26;515,9
				2025-03-26;221,99
				2025-03-26;433,02
				2025-03-26;974,57
				2025-03-27;567,67
				2025-03-27;1379,39
				2025-03-27;321,17
				2025-03-28;1993,93
				2025-03-28;1041,22
				2025-03-28;390,71
				2025-03-29;510,01
				2025-03-29;1958,89
				2025-03-30;1923,95
				2025-03-30;1234,68
				2025-03-30;673,28
				2025-03-30;1515,61
				2025-03-31;663,63
				2025-03-31;1749,88
				2025-03-31;383,06
				2025-04-01;884,53
				2025-04-01;1780,16
				2025-04-01;1121,33
				2025-04-01;1486,11
				2025-04-01;430,37
				2025-04-01;1464,96
				2025-04-02;1017,38
				2025-04-02;1040,98
				2025-04-02;1900,38
				2025-04-03;1615,89
				2025-04-03;1180,36
				2025-04-03;1810,49
				2025-04-03;378,26
				2025-04-04;386,27
				2025-04-04;1006
				2025-04-04;463,51
				2025-04-04;1372,78
				2025-04-05;1214
				2025-04-05;282,65
				2025-04-06;742,11
				2025-04-06;1556
				2025-04-07;296,43
				2025-04-07;1722,17
				2025-04-07;1793,26
				2025-04-07;1912,42
				2025-04-07;559,91
				2025-04-08;845,43
				2025-04-09;1468,36
				2025-04-09;693,75
				2025-04-09;1533,12
				2025-04-10;1460,65
				2025-04-10;1123,46
				2025-04-11;1806,18
				2025-04-11;1829,52
				2025-04-11;1250,42
				2025-04-12;828,88
				2025-04-12;521,33
				2025-04-13;439,93
				2025-04-13;1175,22
				2025-04-16;1066,3
				2025-04-16;251,73
				2025-04-17;724,5
				2025-04-18;1066,67
				2025-04-18;1377,48
				2025-04-19;1394,18
				2025-04-20;1944,67
				2025-04-20;726,05
				2025-04-20;725,63
				2025-04-21;1450,68
				2025-04-21;1040,52
				2025-04-21;239,73
				2025-04-21;1334,83
				2025-04-21;1141,7
				2025-04-21;1171,67
				2025-04-23;1859,01
				2025-04-23;1257,14
				2025-04-23;220,7
				2025-04-24;1193,87
				2025-04-24;322,25
				2025-04-24;1311,37
				2025-04-25;485,11
				2025-04-25;1678,08
				2025-04-25;969,7
				2025-04-25;1590,86
				2025-04-25;1516,48
				2025-04-25;1598,05
				2025-04-26;675,97
				2025-04-27;907,07
				2025-04-27;1635,41
				2025-04-27;1828,03
				2025-04-27;1715,54
				2025-04-27;1402,5
				2025-04-27;1365,73
				2025-04-28;1905,05
				2025-04-28;1808,04
				2025-04-28;1494,17
				2025-04-28;1131,46
				2025-04-29;479,99
				2025-04-29;1012,45
				2025-04-29;934,35
				2025-04-30;1039,44
				2025-04-30;872,23
				2025-04-30;1695,82
				2025-04-30;1267,15
				2025-04-30;292,87
				2025-05-01;1238,34
				2025-05-01;1432,65
				2025-05-02;611,4
				2025-05-02;275,07
				2025-05-03;1730,93
				2025-05-03;471,9
				2025-05-04;849,72
				2025-05-04;1852,98
				2025-05-04;1911,62
				2025-05-05;404,9
				2025-05-05;1510,55
				2025-05-07;1341,79
				2025-05-07;1679,83
				2025-05-07;1270,47
				2025-05-07;1493,89
				2025-05-07;1001,5
				2025-05-08;912,5
				2025-05-08;1437,47
				2025-05-08;813,34
				2025-05-08;1467,29
				2025-05-08;1298,24
				2025-05-08;576,17
				2025-05-09;1144,44
				2025-05-09;1252,12
				2025-05-09;1691,39
				2025-05-10;851,8
				2025-05-10;1323,79
				2025-05-10;917,06
				2025-05-10;620,99
				2025-05-10;1023,44
				2025-05-10;1984,56
				2025-05-11;1036,92
				2025-05-11;776,5
				2025-05-11;660
				2025-05-13;896,74
				2025-05-14;1355,09
				2025-05-14;442,7
				2025-05-14;286,45
				2025-05-14;658,64
				2025-05-15;1831,06
				2025-05-16;424,17
				2025-05-17;541,25
				2025-05-18;1625,72
				2025-05-19;1731,54
				2025-05-19;1843,68
				2025-05-19;508,37
				2025-05-20;1768,03
				2025-05-20;439,87
				2025-05-20;1751,6
				2025-05-20;1977,01
				2025-05-21;1472,03
				2025-05-21;863,92
				2025-05-22;1005,26
				2025-05-22;778,49
				2025-05-22;548,64
				2025-05-23;1081,53
				2025-05-24;1463,97
				2025-05-24;1625,01
				2025-05-24;1779,16
				2025-05-24;1856,14
				2025-05-24;1737,87
				2025-05-25;882,1
				2025-05-26;985,55
				2025-05-26;1030,38
				2025-05-26;1717,93
				2025-05-27;1106,48
				2025-05-27;543,01
				2025-05-27;296,18
				2025-05-28;1743,92
				2025-05-28;1457,78
				2025-05-29;1083,92
				2025-05-29;1329,43
				2025-05-29;1527,06
				2025-05-29;275,56
				2025-05-30;1420,69
				2025-05-30;440,54
				2025-05-30;1954,39
				2025-05-30;1145,71
				2025-05-31;1759,08
				2025-05-31;478,18
				2025-06-01;344,65
				2025-06-01;1364,33
				2025-06-02;1011,39
				2025-06-03;284,77
				2025-06-04;777,94
				2025-06-04;212,11
				2025-06-04;1682,67
				2025-06-04;1230,46
				2025-06-04;569,56
				2025-06-05;1931,48
				2025-06-05;1761,58
				2025-06-05;1758,55
				2025-06-05;249,08
				2025-06-06;1239,32
				2025-06-06;332,8
				2025-06-06;328,94
				2025-06-07;1055,63
				2025-06-07;1155,9
				2025-06-07;434,21
				2025-06-07;1159,26
				2025-06-08;480,93
				2025-06-08;1708,55
				2025-06-09;525,05
				2025-06-10;1980,88
				2025-06-10;514,27
				2025-06-11;983,49
				2025-06-11;348,86
				2025-06-11;1948,53
				2025-06-13;1991,61
				2025-06-13;1219,32
				2025-06-13;1517,45
				2025-06-13;917,93
				2025-06-13;532,7
				2025-06-14;1328,8
				2025-06-14;602,76
				2025-06-14;998,64
				2025-06-14;554,05
				2025-06-15;490,91
				2025-06-15;1815,77
				2025-06-16;1040,98
				2025-06-16;1153,03
				2025-06-16;1792,77
				2025-06-16;670,41
				2025-06-17;745,18
				2025-06-18;1797,57
				2025-06-18;1695,76
				2025-06-18;493,68
				2025-06-18;1124,09
				2025-06-18;1271,23
				2025-06-18;363,6
				2025-06-18;955,51
				2025-06-18;1455,71
				2025-06-19;1320,51
				2025-06-19;470,3
				2025-06-20;1917,48
				2025-06-20;1281,15
				2025-06-21;877,03
				2025-06-21;1264,17
				2025-06-21;1139,68
				2025-06-21;954,36
				2025-06-21;1703,5
				2025-06-22;1134,73
				2025-06-22;510,99
				2025-06-22;1900,22
				2025-06-22;1896,29
				2025-06-23;1651,69
				2025-06-23;570,58
				2025-06-23;1477,55
				2025-06-24;1861,46
				2025-06-24;1184,16
				2025-06-24;1230,66
				2025-06-24;1101,86
				2025-06-25;1362,96
				2025-06-25;1703,89
				2025-06-25;1453,62
				2025-06-25;1707,5
				2025-06-26;1579,71
				2025-06-26;952,12
				2025-06-26;1600,69
				2025-06-27;1638,23
				2025-06-27;615,99
				2025-06-27;232,05
				2025-06-27;1994,07
				2025-06-28;1941,14
				2025-06-28;1868,57
				2025-06-29;1455,92
				2025-06-29;1420,62
				2025-06-30;1675,59
				2025-07-01;493,11
				2025-07-01;741,28
				2025-07-01;494,69
				2025-07-01;1632,59
				2025-07-01;1251
				2025-07-02;1064,29
				2025-07-02;1523,56
				2025-07-02;1511,67
				2025-07-02;997,2
				2025-07-02;580,56
				2025-07-03;1900,18
				2025-07-03;1385,83
				2025-07-04;581,28
				2025-07-04;292,08
				2025-07-04;1600,54
				2025-07-04;925,31
				2025-07-05;1451,5
				2025-07-05;1041,18
				2025-07-05;1538,84
				2025-07-06;1426,67
				2025-07-06;1571,38
				2025-07-06;1011,96
				2025-07-06;1131,79
				2025-07-07;1491,33
				2025-07-07;208,65
				2025-07-08;399,24
				2025-07-08;826,71
				2025-07-08;1358,14
				2025-07-08;451,2
				2025-07-08;1030,41
				2025-07-09;1022,06
				2025-07-10;1238,48
				2025-07-10;1355,81
				2025-07-10;846,26
				2025-07-10;249,29
				2025-07-11;1815,39
				2025-07-11;1071,87
				2025-07-11;223,84
				2025-07-12;1228,24
				2025-07-12;507,26
				2025-07-12;685,65
				2025-07-12;1744,36
				2025-07-13;1042,96
				2025-07-13;258,62
				2025-07-13;632,25
				2025-07-13;1236,28
				2025-07-13;688,69
				2025-07-14;491,23
				2025-07-14;1980,77
				2025-07-14;241,23
				2025-07-15;1241,13
				2025-07-15;1840,13
				2025-07-15;1096,41
				2025-07-16;872,92
				2025-07-16;576,31
				2025-07-16;1658,91
				2025-07-16;1927,03
				2025-07-16;1471,45
				2025-07-17;400,92
				2025-07-17;499,2
				2025-07-18;528,71
				2025-07-18;261,71
				2025-07-18;832,24
				2025-07-18;1471,55
				2025-07-18;304,32
				2025-07-19;1944,18
				2025-07-19;811,39
				2025-07-19;875,21
				2025-07-19;1557,71
				2025-07-20;868,66
				2025-07-20;1514,88
				2025-07-21;1752,3
				2025-07-21;1507,95
				2025-07-22;869,46
				2025-07-23;1036,95
				2025-07-23;258,93
				2025-07-23;957,03
				2025-07-23;1497,09
				2025-07-24;1838,6
				2025-07-24;1169,89
				2025-07-24;1209,2
				2025-07-25;1604,06
				2025-07-26;397,97
				2025-07-26;912,59
				2025-07-26;575,83
				2025-07-26;1796,04
				2025-07-27;1485,35
				2025-07-27;1620,98
				2025-07-28;1774,4
				2025-07-28;1914,26
				2025-07-28;583,55
				2025-07-28;1438,06
				2025-07-29;1418,85
				2025-07-29;1753,85
				2025-07-29;1621,92
				2025-07-29;852,63
				2025-07-31;1066,6
				2025-08-01;357,56
				2025-08-01;888,75
				2025-08-01;1791,46
				2025-08-02;590,37
				2025-08-02;546,12
				2025-08-02;1313,88
				2025-08-03;1610,6
				2025-08-04;1392,01
				2025-08-04;1266,35
				2025-08-04;1360,54
				2025-08-04;1380,62
				2025-08-04;695,17
				2025-08-04;1442,37
				2025-08-04;1346,98
				2025-08-05;1447
				2025-08-05;594,49
				2025-08-05;381,59
				2025-08-05;1208,68
				2025-08-05;1805,91
				2025-08-06;728,06
				2025-08-06;1225,39
				2025-08-07;997,11
				2025-08-07;417,28
				2025-08-08;1284,9
				2025-08-09;1782,19
				2025-08-09;925,71
				2025-08-10;1782,37
				2025-08-10;1092,06
				2025-08-11;1731,03
				2025-08-11;385,71
				2025-08-11;821,19
				2025-08-11;1858,81
				2025-08-11;432,25
				2025-08-11;1852,08
				2025-08-12;1764,85
				2025-08-12;826,92
				2025-08-13;1830,38
				2025-08-13;924,76
				2025-08-13;1585,2
				2025-08-14;742,34
				2025-08-14;1368,47
				2025-08-14;680,62
				2025-08-15;837,6
				2025-08-15;906,81
				2025-08-15;1439,61
				2025-08-16;344,52
				2025-08-17;1406,73
				2025-08-17;1203,58
				2025-08-17;389
				2025-08-18;1946,91
				2025-08-18;1034,61
				2025-08-18;592,21
				2025-08-18;1294,18
				2025-08-20;1459,22
				2025-08-20;753,45
				2025-08-21;1262,66
				2025-08-21;649,39
				2025-08-21;775,83
				2025-08-21;1780,56
				2025-08-22;1356,59
				2025-08-22;317,26
				2025-08-22;451,92
				2025-08-22;1758,79
				2025-08-22;250,53
				2025-08-23;503,73
				2025-08-23;396,34
				2025-08-24;1203,71
				2025-08-24;447,98
				2025-08-24;1578,53
				2025-08-25;1546,61
				2025-08-26;1837,42
				2025-08-27;622,32
				2025-08-27;655,28
				2025-08-28;1991,28
				2025-08-30;981,93
				2025-08-30;566,75
				2025-08-30;1071,1
				2025-08-30;758,38
				2025-08-30;1427,66
				2025-08-31;1260,27
				2025-08-31;779,79
				2025-09-01;1873,27
				2025-09-01;1815,16
				2025-09-01;1724,5
				2025-09-01;1747,02
				2025-09-01;690,05
				2025-09-01;1421,21
				2025-09-02;1894,37
				2025-09-02;319,42
				2025-09-02;1381,48
				2025-09-03;1696,02
				2025-09-03;1549,87
				2025-09-03;648,83
				2025-09-04;1077,25
				2025-09-04;794,62
				2025-09-05;1379,05
				2025-09-05;1591,48
				2025-09-06;1232,45
				2025-09-06;1841,33
				2025-09-07;1001,45
				2025-09-07;1693,98
				2025-09-08;974,54
				2025-09-08;867,99
				2025-09-08;1756,42
				2025-09-09;1273,97
				2025-09-09;1569,59
				2025-09-10;711,02
				2025-09-10;1502,91
				2025-09-10;1898,05
				2025-09-11;557,3
				2025-09-11;1507,99
				2025-09-12;617,64
				2025-09-12;1157,14
				2025-09-13;601,07
				2025-09-14;797,18
				2025-09-14;894,55
				2025-09-14;1228,63
				2025-09-15;465,17
				2025-09-15;677,24
				2025-09-16;619,33
				2025-09-16;734,27
				2025-09-16;527,34
				2025-09-16;817,97
				2025-09-16;687,96
				2025-09-17;695,72
				2025-09-17;1559,08
				2025-09-17;283,58
				2025-09-18;972,95
				2025-09-18;515,45
				2025-09-19;1704,86
				2025-09-19;1520,66
				2025-09-19;1885,26
				2025-09-20;1972,34
				2025-09-21;902,04
				2025-09-21;704,09
				2025-09-21;1217,61
				2025-09-21;527,73
				2025-09-22;466,09
				2025-09-23;865,4
				2025-09-23;1487,24
				2025-09-23;1349,47
				2025-09-23;1540,05
				2025-09-24;1202,26
				2025-09-24;1058,16
				2025-09-24;653,6
				2025-09-24;354,31
				2025-09-26;1215,43
				2025-09-26;1388,2
				2025-09-27;694,93
				2025-09-27;1668,09
				2025-09-27;1022,79
				2025-09-27;255,82
				2025-09-27;1339,68
				2025-09-27;1838,48
				2025-09-28;1840,42
				2025-09-28;1875,2
				2025-09-28;1655,57
				2025-09-28;1541,9
				2025-09-29;1064,18
				2025-09-29;1875,09
				2025-09-29;1636,91
				2025-09-30;1080,6
				2025-09-30;1521,4
				2025-10-01;790,98
				2025-10-02;1565,87
				2025-10-02;1218,4
				2025-10-02;1798,22
				2025-10-02;1307,07
				2025-10-03;1606,68
				2025-10-03;1088,36
				2025-10-04;464,46
				2025-10-04;1263,67
				2025-10-05;917,62
				2025-10-05;763,68
				2025-10-06;1156,96
				2025-10-06;1050,91
				2025-10-06;1295,1
				2025-10-06;1891,79
				2025-10-07;1114,15
				2025-10-07;1499,25
				2025-10-09;1536,38
				2025-10-09;984,62
				2025-10-09;327,35
				2025-10-09;1056,94
				2025-10-09;231,9
				2025-10-10;1822,77
				2025-10-11;1038,95
				2025-10-11;242,73
				2025-10-11;684,64
				2025-10-12;1421,01
				2025-10-12;1977,92
				2025-10-13;539,9
				2025-10-13;1073,72
				2025-10-13;1581,58
				2025-10-13;1482,03
				2025-10-14;1225,73
				2025-10-14;981,86
				2025-10-14;330,83
				2025-10-15;1104,74
				2025-10-15;880,08
				2025-10-15;1659,88
				2025-10-15;1218,83
				2025-10-15;1639,32
				2025-10-16;647,58
				2025-10-17;851,97
				2025-10-18;701,68
				2025-10-18;1920,76
				2025-10-18;925,41
				2025-10-19;1558,65
				2025-10-19;1075,3
				2025-10-20;633,24
				2025-10-22;1642,59
				2025-10-22;1476,63
				2025-10-22;1682,92
				2025-10-23;1211,73
				2025-10-24;1362,2
				2025-10-24;1329,77
				2025-10-25;1196,81
				2025-10-25;693,63
				2025-10-25;1795,14
				2025-10-25;1335,11
				2025-10-25;740,49
				2025-10-26;562,68
				2025-10-26;460,65
				2025-10-26;913,48
				2025-10-26;1454,47
				2025-10-27;1088,19
				2025-10-27;1679,46
				2025-10-28;1292,07
				2025-10-29;330,23
				2025-10-29;1657,46
				2025-10-29;354,3
				2025-10-29;1748,27
				2025-10-29;440,54
				2025-10-29;1509,94
				2025-10-29;702,64
				2025-10-29;1168,73
				2025-10-29;1938,84
				2025-10-30;334,57
				2025-10-30;889,59
				2025-10-30;1488,38
				2025-10-30;1672,43
				2025-10-31;1975,81
				2025-10-31;325,61
				2025-11-01;1913,02
				2025-11-01;654,97
				2025-11-01;1151,91
				2025-11-02;1951,72
				2025-11-02;260,09
				2025-11-04;1856,78
				2025-11-04;598,53
				2025-11-05;1877,43
				2025-11-05;858,81
				2025-11-05;865,99
				2025-11-06;582,25
				2025-11-06;1755,07
				2025-11-07;1140,88
				2025-11-07;1137,74
				2025-11-07;825,6
				2025-11-07;1478,81
				2025-11-08;1138,91
				2025-11-08;723,77
				2025-11-08;1312,88
				2025-11-08;310,44
				2025-11-08;1275,79
				2025-11-08;1877,13
				2025-11-08;663,98
				2025-11-09;1736,42
				2025-11-09;1768,43
				2025-11-09;921,45
				2025-11-09;1155,94
				2025-11-10;1430,67
				2025-11-11;1915,07
				2025-11-11;244,4
				2025-11-11;810,31
				2025-11-12;1347,04
				2025-11-12;1241,21
				2025-11-12;717,11
				2025-11-13;1797,19
				2025-11-13;227,76
				2025-11-14;1427,85
				2025-11-16;1669,06
				2025-11-16;1073,27
				2025-11-16;1256,34
				2025-11-17;1461,11
				2025-11-17;1892,41
				2025-11-18;760,41
				2025-11-20;340,84
				2025-11-20;1093,65
				2025-11-20;1515,21
				2025-11-21;741,27
				2025-11-21;1146,68
				2025-11-21;1933,86
				2025-11-22;376,03
				2025-11-22;1339,86
				2025-11-22;1109,88
				2025-11-23;757,16
				2025-11-23;259,3
				2025-11-23;371,42
				2025-11-24;1497,8
				2025-11-25;1979,56
				2025-11-26;1875,5
				2025-11-26;893,19
				2025-11-26;1864,6
				2025-11-26;715,88
				2025-11-26;1353,25
				2025-11-27;1823,53
				2025-11-27;425,55
				2025-11-27;418,88
				2025-11-27;1553,14
				2025-11-27;1209
				2025-11-28;1135,14
				2025-11-28;1330,27
				2025-11-28;1770,33
				2025-11-29;1413,26
				2025-11-29;1340,97
				2025-11-30;1898,4
				2025-11-30;1845,8
				2025-12-01;1808,11
				2025-12-02;692,08
				2025-12-02;361,28
				2025-12-03;376,23
				2025-12-03;598,33
				2025-12-05;960,15
				2025-12-06;1533,38
				2025-12-06;1770,13
				2025-12-06;383,04
				2025-12-06;417,87
				2025-12-06;1847,52
				2025-12-07;1123,55
				2025-12-08;1822,46
				2025-12-08;1214,04
				2025-12-08;553,29
				2025-12-09;822,03
				2025-12-09;1876,75
				2025-12-10;1881,64
				2025-12-10;1129,18
				2025-12-10;1689,71
				2025-12-10;1028,06
				2025-12-10;1529,03
				2025-12-11;1855,42
				2025-12-11;1270,6
				2025-12-11;1912,79
				2025-12-11;1307,79
				2025-12-11;630,31
				2025-12-12;1873,02
				2025-12-13;721,72
				2025-12-13;829,57
				2025-12-14;462,19
				2025-12-15;1580,17
				2025-12-15;1184,42
				2025-12-15;799,38
				2025-12-15;468,92
				2025-12-15;780,6
				2025-12-16;1149,11
				2025-12-16;375,66
				2025-12-16;1776,45
				2025-12-16;468,29
				2025-12-17;735,62
				2025-12-17;300,43
				2025-12-17;1087,06
				2025-12-17;1956,7
				2025-12-18;1994,62
				2025-12-18;328,32
				2025-12-19;964,48
				2025-12-19;309,94
				2025-12-19;549,77
				2025-12-19;309,16
				2025-12-19;1516,46
				2025-12-20;1313,32
				2025-12-20;1010,11
				2025-12-22;1458,03
				2025-12-22;411,52
				2025-12-23;1628,92
				2025-12-24;1207,85
				2025-12-24;816,39
				2025-12-24;911,76
				2025-12-25;512,53
				2025-12-26;1880,32
				2025-12-26;1233,98
				2025-12-27;1640,98
				2025-12-27;1483,27
				2025-12-27;614,6
				2025-12-28;1304,25
				2025-12-28;467,29
				2025-12-29;1779,85
				2025-12-29;569,63
				2025-12-29;1736,13
				2025-12-29;887,75
				2025-12-30;1820,55
				2025-12-30;1158,32
				2025-12-30;1115,93",
				    CsvExtraido = Table.PromoteHeaders(Csv.Document(Fonte, [Delimiter=";"])),
				    TipoAlterado = Table.TransformColumnTypes(CsvExtraido,{{"DataVencimento", type date}, {"Valor", Currency.Type}})
				in
				    TipoAlterado
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

